### ISSUE TITLE
Create a dashboard page

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#10]
This ticket will track the creation of the dashboard page.

- [x] Create initial dashboard page
- [x] Reviewed by team
- [x] Reconcile edits
- [x] Second team review
- [x] Merge to main

Note that even after merged to main, work on the page may still continue.

**Comment by RakeshPerani** [comment]
will start on dashboard this weekend

**Comment by RakeshPerani** [comment]
rough draft of dashboard page complete with some CSS. Need input on font and font sizes.

**Comment by RakeshPerani** [comment]
Dashboard completed with Forum, Listings, Edit Profile, and Logout Buttons. Used this site for CSS for buttons: https://codepen.io/sarath-ar/pen/dMKxxM
