### ISSUE TITLE
Create a forum page

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#12]
This ticket will track the creation of the forum page.

- [x] Create initial forum page
- [x] Reviewed by team
- [x] Reconcile edits
- [x] Second team review
- [x] Merge to main

Note that even after merged to main, work on the page may still continue.

**Comment by joe-bollinger** [comment]
Initial page created with models. Updated files as needed, but still needs work.

**Comment by joe-bollinger** [comment]
Forum page completed with post and search forms with pagination. First review by team with suggestions made to styling. Styling updated as suggested, and reviewed by team OKed and merged to main.

**Comment by RakeshPerani** [comment]
Good job Joe.
