### ISSUE TITLE
Create a listings page

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#13]
This ticket will track the creation of the listings page.

- [x] Create initial listings page
- [x] Reviewed by team
- [x] Reconcile edits
- [x] Second team review
- [x] Merge to main

Note that even after merged to main, work on the page may still continue.

**Comment by RakeshPerani** [comment]
Createda functional profile listings page with Joe that lists: user name, profile image, date joined, and bio.

**Comment by RakeshPerani** [comment]
Still needs card styling.

**Comment by RakeshPerani** [comment]
Worked on listings styling. Please check it. I removed the nav bar at the top. We can add it back if you want to.

**Comment by RakeshPerani** [comment]
Listings css pushed from rakesh-dashboard branch

**Comment by RakeshPerani** [comment]
Listings.html completed with navigation bar for profile, logout, and forums pages.
