### ISSUE TITLE
Create a view profile page

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#14]
This ticket will track the creation of the view profile page.

- [x] Create initial view profile page
- [x] Reviewed by team
- [x] Reconcile edits
- [x] Second team review
- [x] Merge to main

Note that even after merged to main, work on the page may still continue.

**Comment by KaOus22** [comment]
I am getting a merge conflict from rcjourney/db.sqlite3 when I try to pull onto my branch.

**Comment by brett-buskirk** [comment]
> @brett-buskirk I am getting a merge conflict from rcjourney/db.sqlite3 when I try to pull onto my branch. I am going to delete my current branch and create a new one to try to fix this as I have not done any work on my branch yet.

You're going to get a conflict because technically you changed something in the sqlite database by installing and running the files. You can commit the changes to the dev branch  you're working on, then switch to the main branch to pull.

**Comment by KaOus22** [comment]
Deleting the branch is not allowed until we fix the merge conflict.

**Comment by KaOus22** [comment]
Resolved the issue by adding db.sqlite3

**Comment by RakeshPerani** [comment]
Good job on the page and CSS. Delete functionality and button added posts in profile.html.
