### ISSUE TITLE
Create script to drop and populate database

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#22]
Need to create a script that will drop existing database entries and populate it with sample data.

**Comment by brett-buskirk** [comment]
[Here](https://www.sqlite.org/cli.html#converting_an_entire_database_to_a_text_file) is a method to accomplish this task

**Comment by brett-buskirk** [comment]
Seeing as everyone is on different operating systems and some don't have access to certain commands, I thought it best to find a solution that utilizes the python native to the project's environment. As such, I came up with the following:

To dump the database, a user needs to be in their virtual environment and run `python manage.py dbshell`. After that, they will need to run the following sqlite shell commands:

```
sqlite> .output db.dump.sql
sqlite> .dump
sqlite> .exit
```

To import data from the SQL file, similarly they need to be in the virtual environment and run `python manage.py dbshell`. If the `db.sqlite3` database already exists, it should first be deleted. Then the following sqlite commands need to be run from the shell:

```
sqlite> .read db.dump.sql
sqlite> .exit
```

After this, the database should be created.

**Comment by RakeshPerani** [comment]
db.sqlite3 issue circumvented by not pushing/pulling db.sqlite3.
