### ISSUE TITLE
Create app pages

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/rc-journey#9]
The following pages need to be created in order to complete the app as submitted:

- [x] #6 
- [x] #8 
- [x] #7
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14

**Comment by brett-buskirk** [comment]
Hey team! This ticket will track the overall creation of our app. After we decide who will be building which pages, please click on the associated ticket and assign yourself to it. We can use this ticket as a place for general conversation about the overall structure of the pages, but we'll use the individual page tickets to discuss topics related to that particular page.

**Comment by brett-buskirk** [comment]
I've already assigned myself to the landing, register, and login pages since they comprise most of the authentication involved with the app. @KaOus22 and @joe-bollinger, feel free to open a discussion about what pages you would like to tackle.

**Comment by KaOus22** [comment]
@brett-buskirk , @joe-bollinger , @RakeshPerani  

I created pages for: forums, listings, profile, and edit. I have created views and links for each of these pages on the dashboard for now. I have not styled them yet, but I am going to go ahead and push them up so we can begin working on our individual pages accordingly.

**Comment by brett-buskirk** [comment]
All app pages have been created, reviewed, revised, and merged into main.
